<a href="https://colab.research.google.com/github/devidrees/DA-Python-AUG/blob/main/function_and_NUMPY_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Function in programming

- box of instructions
- task 1
- task 2
- task 3
-
-

real work you want all the instructions to run
- def tasks():
    task 1
    task 2
    task 3
- tasks(2)

In [ ]:
# variable object
input = 60
print(input)

# function object is coming up
# you can store many variable, many instructions
def function_name():
  return 0

# class object is incoming
# you can have many functions, many variables
class idrees():
  var = 10
  def greet():
    print("idrees")

60


In [ ]:
def greet():
  print("Idrees")
  print("Idrees")
  print("Idrees")
  print("Idrees")
  print("Idrees")
  print("Idrees")
  print("Idrees")

def idrees_sum(num1 = 0, num2 = 0,  name = "Idrees"): # default parameters - parameters
  sum = num1 + num2
  return f"Hey {name}! The sum is: {sum}"



In [ ]:
idrees_sum()

'Hey Idrees! The sum is: 0'

In [ ]:
greet()

Idrees
Idrees
Idrees
Idrees
Idrees
Idrees
Idrees


### Function Scope (Local Scope)

In [ ]:
# global scope
# accessible anywhere in the program
input = 20 # global variable - can be accessed anywhere
#print(input)

# Create a function that takes a number, and returns the square of the number
def sq(num): # parameters
  # function scope
  square = num * num
  x = 23 # local variables - only accessible inside a function
  y = input
  return square

# function call
sq(55555) # argument

3086358025

## Lambda Fuction
- small, one line fuctions, anonymous function

```python
lambda parameters : expression

variable_name = lambda x, y : <expression of x and y>
```


In [ ]:
# Lambda Functions
# to calculate cube of a number

#   parameter
#     input        return
cube = lambda  x:   x**3 # exponent **

#  argument - real input
cube(3)


### give me a lambda function to calculate addition of two numbers
add = lambda  x,y:   x+y

add(2,3) # result in 5

## lambda function to double a number
double = lambda  x:   x*2
double(100)

27

### Error Handling
- Programming
- Try Except Method
-

- Logging:



## Libraries
- object oriented language: everything is an object
- every object is an instance of a class
-
- variables, conditionals, logic, loops
- functions - lots of variables, or operation or conditionals
- Class - can house a lot of functions, variables
-
- Module - can contain a lot of classes - a script file
- Libraries/ or package - Can contain a lot of modules

**variables < functions < classes < modules < libraries**

- Libraries - are prewritten code that we can reuse easily

## **Numpy**
- In built libraries
  - import math
  - import time
  - import sys
- Libraies that python developers created and we still use
- in cmd
> `pip install numpy`
- it is so important, creator of python actually mentioned we were very close to add `numpy` to the main python
- if you are inside of a jupyter notebook e.g. in google colab then use of `!` - run this code in Terminal (command prompt or cmd)

- in google colab, some of these libraries come inbuilt
- how to test that?
- `import numpy as np`

In [ ]:
pip install numpy

- built for numerical calculations
  - what is the reason for that?
  - because: Numpy uses ARRAYs
  - and arrays are **FAST** and **memory efficient**
-
-
- Linear Algebra: x + 2y = 10
-


In [64]:
# list slicing

list_a = [1,2,3,4,5,6,7,8,9,10]

# access elements from start to 5th element
list_a[0:5] # elements upto 4th index
list_a[0:10:2]  # start, stop, step_size



[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [67]:
import numpy as np

# python list
name = ["idrees", "john", "bob"]
age = [24, 27, 29]
experience = [7, 10, 5]

table_list = [name, age, experience]
print(table_list)

# access elements in a list
table_list[0][2] # bob - 1D kya - resulting array mai kya

[['idrees', 'john', 'bob'], [24, 27, 29], [7, 10, 5]]


'bob'

In [72]:
# 1D arrays
name_arr = np.array(name) # name becomes the python list argument here
age_arr = np.array(age)
exp_arr = np.array(experience)

# 2D array
# in arrays, we should always have same type of data
# having different types might work - arrays speed effiency is gone

#                         text    number  number
table_arr = np.array([name_arr, age_arr, exp_arr])
print(table_arr)
table_arr.shape
table_arr.dtype

[['idrees' 'john' 'bob']
 ['24' '27' '29']
 ['7' '10' '5']]


dtype('<U21')

In [70]:
# we must always keep similar type of data in one array
# otherwise we will lose the benefit of speed and efficieny
# create an array
arr_a = np.array([1,2,3,4,5,"idrees"])
# this will not give the benefits of an array
type(arr_a)

numpy.ndarray

- every array has a Data Type
  - Number arrays:
    - small numbers: int8 - 8 bits - 2 bytes
    - medium: int16, int32
    - large: int64, int128

In [77]:
arr_b = np.array([99,3,4], dtype = np.int64)
arr_b

array([99,  3,  4], dtype=int8)

In [66]:
# checking data type
age_arr.dtype

dtype('int64')

In [92]:
# array methods
arr_a = np.arange(10) # create an array of 10 elements

# used in creating plots later
arr_a = np.linspace(0, 1, 100) # 100 element
# distributes elements linearly

arr_a = np.zeros((2,3)) # pass a shape as argument here - rows, columns
arr_a = np.ones((2,10))

arr_2d = np.array([
    [1,  2,   3],
    [10, 10, 10],
    [2,   2,  2]
    ])
print(arr_a.ndim)

2


## accessing elements
### slicing and indexing


In [93]:
print(arr_2d)

[[ 1  2  3]
 [10 10 10]
 [ 2  2  2]]


In [102]:
# slicing - Start : End : Step_size - End is excluded
arr_2d[0:3]
# :

# what if i want a subset of this array
# i only want the 10 10 2, 2 - right bottom quadrant
# interview

# indexing - [rows, cols] - [slice of rows, slice of columns]

# ,
# :

arr_2d[1,2] # just like coordinates - you can get elements out of arrays
arr_2d[1:3, 1:3]

array([[10, 10],
       [ 2,  2]])

In [97]:
arr_2d.size # how many elements
arr_2d.ndim
arr_2d.shape
arr_2d.dtype

dtype('int64')

- numpy: non-tech
  - numpy arrays
  - arrays efficiency
  - Array methods - shape, .dim, .dtype - jitne seekh paao
  - Array elements accessing - slicing, indexing
  - element wise multiplications - Broadcasting

In [107]:
# list multiply
list_a = [1,  2,   3,  4,  5]
list_b = [10, 20, 30]

list_a * 2 # list can mulitply with a scalar - number

"a" * 4

list_a + list_b # concatenate - JOIN
list_a * list_b

TypeError: can't multiply sequence by non-int of type 'list'

In [115]:
np.array([1,  2,   3]).shape # row vector - (3,)
np.array([[1], [2],   [3]]).shape # column vector - (3,1)

(3, 1)

In [122]:
arr_a = np.array([1,  2,   3,  4,  5])
arr_b = np.array([10, 20, 30, 40, 50])


arr_a = np.array([100, 200, 300]) # (1, 3) - (3,)

arr_b =np.array([[10, 20, 30], # (7,3)
                 [10, 20, 30],
                 [10, 20, 30],
                 [10, 20, 30],
                 [10, 20, 30],
                 [10, 20, 30],
                 [10, 20, 30]])


arr_a = np.array([[100, 200], # 2,2
                 [100, 200]])

arr_b = np.array([[10], # 2,1
                 [10]])

# BROADCASTING -
arr_a * 10

# here element wise operations occur
# you have make sure the dimensions align
arr_a * arr_b

# BASIS OF ALL AI, ML and DL
# Matrix multiplication
arr_a @ arr_b

# LLMs # Attention - its a matrix multiplication

array([[3000],
       [3000]])




## Pandas


## Matplotlib/ Seaborn


## Data Cleaning Project